{{- if and .Values.ingress.enabled (not .Values.ingress.traefik.enabled) }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  annotations:
    {{- if .Values.ingress.sslRedirect }}
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    {{- end }}
    {{- with .Values.ingress.customAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    {{- range $host := .Values.ingress.hosts }}
    - host: {{ $host.host }}
      http:
        paths:
        {{- range $path := $host.paths }}
        - path: {{ $path.path }}
          pathType: {{ default "ImplementationSpecific" $path.pathType}}
          backend:
            service:
              name: {{- if hasKey $path "serviceName" -}}
                      {{- $path.serviceName | indent 1}}
                    {{- else if hasKey $.Values.irisapp "name" -}}
                      {{- $.Values.irisapp.name | indent 1}}
                    {{- else -}}
                      {{- fail "Missing 'serviceName' in ingress.hosts[].paths[] and no default in irisapp.name" }}
                    {{- end }}
              port:
                number: {{- if hasKey $path "servicePort" -}}
                          {{- printf "%v" $path.servicePort | indent 1}}
                        {{- else if hasKey $.Values.irisapp.service "port" -}}
                          {{- printf "%v" $.Values.irisapp.service.port | indent 1 }}
                        {{- else -}}
                          {{- fail "Missing 'servicePort' in ingress.hosts[].paths[] and no default in irisapp.service.port" }}
                        {{- end }}
        {{- end }}
    {{- end }}
  {{- if and .Values.ingress.enableTls (gt (len .Values.ingress.tls.hosts) 0) }}
  tls:
    - hosts:
      {{- range .Values.ingress.tls.hosts }}
      - {{ . }}
      {{- end }}
      secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
{{- end }}