apiVersion: v1
kind: Secret
metadata:
  name: iris-ldap-certs-secret-worker
  labels:
    app: {{ .Values.irisworker.app }}
type: Opaque
data:
{{ (.Files.Glob "certificates/ldap/*").AsSecrets | indent 2 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: iris-certs-dir-webcerts-secrets-worker
  labels:
    app: {{ .Values.irisworker.app }}
type: Opaque
data:
{{ (.Files.Glob "certificates/web_certificates/*").AsSecrets | indent 2 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.irisworker.name }}
spec:
  replicas: {{ .Values.irisworker.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.irisworker.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.irisworker.app }}
    spec:
      securityContext:
        {{- toYaml .Values.irisworker.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.irisworker.name }}
          securityContext:
            {{- toYaml .Values.irisworker.securityContext | nindent 12 }}
          resources:
            {{- toYaml .Values.irisworker.resources | nindent 12 }}
          image: "{{ .Values.irisworker.image}}:{{ .Values.irisworker.tag }}"
          imagePullPolicy: "{{ .Values.irisworker.imagePullPolicy }}"
          command: ['./wait-for-iriswebapp.sh', "{{ .Values.irisapp.name }}:{{ .Values.irisapp.service.port }}", './iris-entrypoint.sh', 'iris-worker']

          env:

          - name: DOCKERIZED
            value: {{ .Values.irisworker.DOCKERIZED | quote }}

          {{- range $key := list "POSTGRES_USER" "POSTGRES_PASSWORD" "POSTGRES_ADMIN_USER" "POSTGRES_ADMIN_PASSWORD" "POSTGRES_PORT" "POSTGRES_SERVER" }}
          - name: {{ $key }}
            {{- if and (hasKey $.Values.irisworker "envFromSecret") (has $key $.Values.irisworker.envFromSecret.keys) }}
            valueFrom:
              secretKeyRef:
                name: {{ $.Values.irisworker.envFromSecret.name }}
                key: {{ $key }}
            {{- else }}
            value: {{ index $.Values.irisworker $key | quote }}
            {{- end }}
          {{- end }}

          - name: CELERY_BROKER
            value: {{ .Values.irisworker.CELERY_BROKER | quote }}

          - name:  IRIS_SECRET_KEY
            value: {{ .Values.irisworker.IRIS_SECRET_KEY | quote }}

          - name:  IRIS_SECURITY_PASSWORD_SALT
            value: {{ .Values.irisworker.IRIS_SECURITY_PASSWORD_SALT | quote }}

          - name: NUMBER_OF_CHILD
            value: {{ .Values.irisworker.NUMBER_OF_CHILD | quote }}


          volumeMounts:
            - mountPath: /home/iris/downloads
              name: iris-downloads
            - mountPath: /home/iris/user_templates
              name: user-templates
            - mountPath: /home/iris/server_data
              name: server-data
            - mountPath: /home/iris/certificates/web_certificates
              name: iris-certs-dir-webcerts
              readOnly: true
            - mountPath: /iriswebapp/certificates/ldap/
              name: iris-ldap-certs
              readOnly: true
      volumes:
        - name: iris-downloads
          emptyDir: {}  
        - name: user-templates
          emptyDir: {}
        - name: server-data 
          emptyDir: {}
        - name: iris-ldap-certs
          secret:
            secretName: iris-ldap-certs-secret-worker
        - name: iris-certs-dir-webcerts
          secret:
            secretName: iris-certs-dir-webcerts-secrets-worker
---
